# Generated by Django 4.2.2 on 2023-07-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(verbose_name='date added')),
                ('description', models.CharField(max_length=250)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_key', to='users.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_key', to='finance_app.category')),
            ],
        ),
    ]
