# Generated by Django 4.2.2 on 2023-08-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ManyToManyField(related_name='categories_key', to='finance_app.category'),
        ),
    ]
